# -*- coding: utf-8 -*-
"""DigitClassifier.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MYcBF9fiNDPZwO6xQqBfJopaPwZin0FC
"""

from tensorflow import keras
def get_classifier():
    #load the data
    mnist = keras.datasets.mnist

    (X_train, Y_train), (X_test, Y_test) = mnist.load_data()
    #normalize the data
    X_min = X_train.min()
    X_max = X_train.max()
    X_train = (X_train - X_min) / (X_max - X_min)
    X_test = (X_test - X_min) / (X_max - X_min)

    #flatten the array into a 2D array
    X_train=X_train.reshape(X_train.shape[0],X_train.shape[1]*X_train.shape[2])
    X_test=X_test.reshape(X_test.shape[0],X_test.shape[1]*X_test.shape[2])

    from sklearn.tree import DecisionTreeClassifier
    clf = DecisionTreeClassifier()
    
    return clf.fit(X_train, Y_train)
